# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('numero', models.AutoField(db_column='NUMERO', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='NOME', max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='DepartamentoProjeto',
            fields=[
                ('codigo', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'departamento_projeto',
            },
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('codigo', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False)),
                ('nome_dependente', models.CharField(blank=True, db_column='NOME_DEPENDENTE', max_length=50, null=True)),
                ('nascimento', models.DateField(blank=True, db_column='NASCIMENTO', null=True)),
                ('relacao', models.CharField(blank=True, db_column='RELACAO', max_length=10, null=True)),
                ('sexo', models.CharField(blank=True, db_column='SEXO', max_length=1, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'dependente',
            },
        ),
        migrations.CreateModel(
            name='Empregado',
            fields=[
                ('rg', models.IntegerField(db_column='RG', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='NOME', max_length=50, null=True)),
                ('cpf', models.CharField(blank=True, db_column='CPF', max_length=10, null=True)),
                ('salario', models.DecimalField(blank=True, db_column='SALARIO', decimal_places=2, max_digits=12, null=True)),
                ('dat_ini_sal', models.DateField(blank=True, db_column='DAT_INI_SAL', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'empregado',
            },
        ),
        migrations.CreateModel(
            name='EmpregadoProjeto',
            fields=[
                ('codigo', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False)),
                ('horas', models.IntegerField(blank=True, db_column='HORAS', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'empregado_projeto',
            },
        ),
        migrations.CreateModel(
            name='HistoricoSalario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_ini_sal', models.DateField(db_column='DAT_INI_SAL')),
                ('dat_fim_sal', models.DateField(db_column='DAT_FIM_SAL')),
                ('salario', models.DecimalField(db_column='SALARIO', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'historico_salario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('numero', models.AutoField(db_column='NUMERO', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='NOME', max_length=50, null=True)),
                ('localizacao', models.CharField(blank=True, db_column='LOCALIZACAO', max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'projeto',
            },
        ),
    ]
