# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto1',
            fields=[
                ('numero', models.AutoField(db_column='NUMERO', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='NOME', max_length=50, null=True)),
                ('localizacao', models.CharField(blank=True, db_column='LOCALIZACAO', max_length=50, null=True)),
            ],
            options={
                'db_table': 'projeto',
                'managed': False,
            },
        ),
    ]
